### ISSUE TITLE
Where Did you load Generator & Decoder Model?

### ISSUE THREAD

**Issue by HRNPH** [Francis-Komizu/Sovits#10]
I'm trying to train a model but I have no idea how did you load the pretrained decoder model which wasn't mention in readme
![image](https://user-images.githubusercontent.com/51855316/232227581-f5b36fe2-aeb5-4053-8a3f-b6d7cd1a5763.png)

**Comment by Francis-Komizu** [comment]
> I'm trying to train a model but I have no idea how did you load the pretrained decoder model which wasn't mention in readme ![image](https://user-images.githubusercontent.com/51855316/232227581-f5b36fe2-aeb5-4053-8a3f-b6d7cd1a5763.png)

Hi, in `train.py`, there are two line that load the lastest generator and discriminator according to their training steps. By default, `hps.model_dir` is `logs\model_name` , where you should put your model. 
```python
_, _, _, epoch_str = utils.load_checkpoint(utils.latest_checkpoint_path(hps.model_dir, "G_*.pth"), net_g,

**Comment by HRNPH** [comment]
Thx for your reply
I've managed to train the model after fixing some dependencies issues and the result is pretty good
so we didn't have a pre-trained generator and decoder model for fine-tuning right?

another question what if I use the default D_0 decoder while replaced the G_0 generator with another pre-trained weight (ex. G_10000)
but didn't change D_0 decoder? like what if I download Shiki natsume Generator

**Comment by Francis-Komizu** [comment]
> 
Hi! If I my understanding is right, when referring to decoder, you mean the D_xxx model, namely the discriminator? 
1. Actually I don't have any pre-trained models for finetuning because the number of speaker(s) have to be set fixed before training. For example, we can't finetune the Shiki Natsume model, which is a single speaker model, using a mutil-speaker dataset.
2. I think that'll work. Since the model uses adversarial training, after some iterations, the D_0 will probably "catch up with" the generator. And by the way, during inference, we only use the generator.

**Comment by HRNPH** [comment]
1. lol sorry, Yes I mean discriminator
2. that makes sense! usually, Discriminator tend to beat the generator
Thx for your reply! I think this can now be closed
